### ISSUE TITLE
gwt-safehtml-processor 1.0.0-RC1 refer to wrong parent (dev version)

### ISSUE THREAD

**Issue by foal** [gwtproject/gwt-safehtml#26]
Check the https://repo1.maven.org/maven2/org/gwtproject/safehtml/gwt-safehtml-processor/1.0.0-RC1/gwt-safehtml-processor-1.0.0-RC1.pom

The parent has a `dev` version which is missing in the Maven Central
  
![image](https://user-images.githubusercontent.com/458209/114313733-f8668500-9af7-11eb-9608-166a4af82cff.png)

P.S. It is better to use the https://www.mojohaus.org/flatten-maven-plugin/ to leave only necessary info in the released POM.

**Comment by FrankHossfeld** [comment]
Yeap ... I see, we missed adding the flatten-maven-plugin after the shade plugin. 

Will fix it.
